<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot2">

  <xacro:property name="B" value="0.04" />
  <xacro:property name="B_radius" value="0.08" />
  <xacro:property name="L1" value="0.18" />
  <xacro:property name="L1radius" value="0.05" />
  <xacro:property name="L2" value="0.12" />
  <xacro:property name="L2radius" value="0.05" />
  <xacro:property name="L3" value="0.0875" />
  <xacro:property name="L3radius" value="0.03" />
  <xacro:property name="eesize" value="0.05" />
  <xacro:property name="J1MIN" value="${-((2*pi)/3)}" />
  <xacro:property name="J1MAX" value="${(2*pi)/3}" />
  <xacro:property name="J2MIN" value="${-((2*pi)/9)}" />
  <xacro:property name="J2MAX" value="${(2*pi)/9}" />
  <xacro:property name="J3MIN" value="-0.04" />
  <xacro:property name="J3MAX" value="0.04" />

  <material name="blue">
    <color rgba="0.2 0.4 0.65 1" />
  </material>

  <material name="yellow">
    <color rgba="1 0.85 0 1" />
  </material>

  <link name="world" />

  <link name="base_link">
    <visual name="base_link">
      <origin xyz="0 0 ${B/2}" />
      <geometry>
        <cylinder radius="${B_radius}" length="${B}" />
      </geometry>
      <material name="blue" />
    </visual>
  </link>

  <link name="link1">
    <visual name="link1">
      <origin xyz="0 0 ${L1/2}" />
      <geometry>
        <cylinder radius="${L1radius}" length="${L1}" />
      </geometry>
      <material name="blue" />
    </visual>
  </link>

  <link name="link2">
    <visual name="link2">
      <origin rpy="0 ${pi/2} 0" xyz="${(L2/2)-(L1radius/2)} 0 0" />
      <geometry>
        <cylinder radius="${L2radius}" length="${L2+(L1radius)}" />
      </geometry>
      <material name="blue" />
    </visual>
  </link>

  <link name="link3">
    <visual name="link3">
      <origin rpy="0 ${pi/2} 0" xyz="${(L3/2) - (J3MAX/2)} 0 0 " />
      <geometry>
        <cylinder radius="${L3radius}" length="${L3+J3MAX}" />
      </geometry>
      <material name="blue" />
    </visual>
  </link>

  <link name="ee">
    <visual name="ee">
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${eesize} ${eesize} ${eesize}" />
      </geometry>
      <material name="yellow" />
    </visual>
  </link>

  <joint name="base_in_world" type="fixed">
    <parent link="world" />
    <child link="base_link" />
    <origin xyz="${-((eesize/2)+L3+L2)} 0 0" />
  </joint>

  <joint name="joint1" type="revolute">
    <parent link="base_link" />
    <child link="link1" />
    <origin rpy="0 0 0" xyz="0 0 ${B}" />
    <axis xyz="0 0 1" />
    <limit lower="${J1MIN}" upper="${J1MAX}" effort="1" velocity="1" />
  </joint>

  <joint name="joint2" type="revolute">
    <parent link="link1" />
    <child link="link2" />
    <origin rpy="0 0 0" xyz="0 0 ${L1}" />
    <axis xyz="0 1 0" />
    <limit lower="${J2MIN}" upper="${J2MAX}" effort="1" velocity="1" />
  </joint>

  <joint name="joint3" type="prismatic">
    <parent link="link2" />
    <child link="link3" />
    <origin rpy="0 0 0" xyz="${L2} 0 0" />
    <axis xyz="1 0 0" />
    <limit lower="${J3MIN}" upper="${J3MAX}" effort="1" velocity="1" />
  </joint>

  <joint name="ee_in_link3" type="fixed">
    <parent link="link3" />
    <child link="ee" />
    <origin xyz="${L3+(eesize/2)} 0 0" rpy="0 0 0" />
  </joint>

</robot>
