<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot3">

  <xacro:property name="L1" value="0.20" />
  <xacro:property name="L1_size" value="0.05" />
  <xacro:property name="L2" value="0.08" />
  <xacro:property name="L2_size" value="0.05" />
  <xacro:property name="L3" value="0.06" />
  <xacro:property name="L3_size" value="0.05" />
  <xacro:property name="L4" value="0.06" />
  <xacro:property name="L4_size" value="0.03" />
  <xacro:property name="ee_size" value="0.04" />
  <xacro:property name="J1MIN" value="-0.08" />
  <xacro:property name="J1MAX" value="0.08" />
  <xacro:property name="J2MIN" value="${-pi/2}" />
  <xacro:property name="J2MAX" value="${pi/2}" />
  <xacro:property name="J3MIN" value="-0.04" />
  <xacro:property name="J3MAX" value="0.04" />

  <material name="blue">
    <color rgba="0.2 0.4 0.65 1" />
  </material>

  <material name="yellow">
    <color rgba="1 0.85 0 1" />
  </material>

  <link name="world" />

  <link name="base" />

  <link name="link1">
    <visual name="link1">
      <origin xyz="0 0 ${(L1+J1MAX+(L2_size/2))/2}" />
      <geometry>
        <box size="${L1_size} ${L1_size} ${L1+J1MAX+L2_size/2}" />
      </geometry>
      <material name="blue" />
    </visual>
  </link>

  <link name="link2">
    <visual name="link2">
      <origin rpy="0 ${pi/2} 0" xyz="${L2/2} 0 0" />
      <geometry>
        <box size="${L2_size} ${L2_size} ${L2}" />
      </geometry>
      <material name="blue" />
    </visual>
  </link>

  <link name="link3">
    <visual name="link3">
      <origin rpy="0 ${pi/2} 0" xyz="${L3/2} 0 0 " />
      <geometry>
        <box size="${L3_size} ${L3_size} ${L3}" />
      </geometry>
      <material name="blue" />
    </visual>
  </link>

  <link name="link4">
    <visual name="link4">
      <origin rpy="0 0 0" xyz="0 0 ${L4/2} " />
      <geometry>
        <box size="${L4_size} ${L4_size} ${L4}" />
      </geometry>
      <material name="blue" />
    </visual>
  </link>

  <link name="ee">
    <visual name="ee">
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${ee_size} ${ee_size} ${ee_size}" />
      </geometry>
      <material name="yellow" />
    </visual>
  </link>

  <joint name="base_in_world" type="fixed">
    <parent link="world" />
    <child link="base" />
    <origin xyz="${-(L4+L3+L2)} 0 0" />
  </joint>

  <joint name="link1_in_base" type="fixed">
    <parent link="base" />
    <child link="link1" />
    <origin xyz="0 0 0" />
  </joint>

  <joint name="joint1" type="prismatic">
    <parent link="link1" />
    <child link="link2" />
    <origin rpy="0 0 0" xyz="0 0 ${L1}" />
    <axis xyz="0 0 1" />
    <limit lower="${J1MIN}" upper="${J1MAX}" effort="1" velocity="1" />
  </joint>

  <joint name="joint2" type="revolute">
    <parent link="link2" />
    <child link="link3" />
    <origin rpy="0 0 0" xyz="${L2} 0 0" />
    <axis xyz="0 0 1" />
    <limit lower="${J2MIN}" upper="${J2MAX}" effort="1" velocity="1" />
  </joint>

  <joint name="joint3" type="prismatic">
    <parent link="link3" />
    <child link="link4" />
    <origin rpy="0 ${pi/2} 0" xyz="${L3} 0 0" />
    <axis xyz="0 0 1" />
    <limit lower="${J3MIN}" upper="${J3MAX}" effort="1" velocity="1" />
  </joint>

  <joint name="ee_in_link4" type="fixed">
    <parent link="link4" />
    <child link="ee" />
    <origin xyz="0 0 ${L4}" rpy="0 ${-pi/2} 0" />
  </joint>

</robot>